# Site settings
title:          "hetnavi."
description:    "Learning by Storytelling"
url:            "https://hetnavi.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         hetnavi
  url:          https://hetnavi.github.io
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus:         jekyll-tale